### ISSUE TITLE
Failable initializers, revisited: Force unwrap in parser?

### ISSUE THREAD

**Issue by iUtvikler** [jessesquires/jessesquires.github.io#10]
Thanks for an awesome article!

Do you use force unwrapping in the parser?

Say I have JSON like this:
```JSON
{
  "id": 1,
  "name": "Lars"
}
```

Would you do something like this:

```swift
typealias JSON = [String: AnyObject]

struct User {
  let id: Int
  let name: String
}

let userValidator = JSONValidator<User> { (json) -> Bool in
  if let
    _ = json["id"] as? Int,
    _ = json["firstname"] as? String
  {
    return true
  }

  return false
}

struct UserParser: JSONParserType {
  func parseJSON(json: JSON) -> User {
    let user = User(
      id: json["id"] as! Int,
      name: json["firstname"] as! String
    )

    return user
  }
}

if let users = parse(json, userValidator, UserParser()) {
  // Stuff..
}
```

Do you think it is better to join the parser and validator to avoid force unwrapping?

**Comment by jessesquires** [comment]
Hey @iUtvikler - Thanks! :smile:  Great question.

I agree that forced unwrapping should be used sparingly and with caution, but in this case we know whether it is safe/unsafe based on the result from the validator. I like the separation of concerns this brings into the parsing flow, and its ability to bail early. For example, if the `"id"` key is missing or if it is a `String` instead of an `Int`, we can bail immediately and we know exactly why — the json isn't valid.

However, I think combining validation and parsing into a single "step/unit" is also valid, and can see why this may work better for many situations. And you can still achieve the properties/semantics above. With this approach, you could use a library like [SwiftyJSON](https://github.com/SwiftyJSON/SwiftyJSON) internally, which is a huge win.

My guess is most will opt use the latter (joining the validator and parser), and likely use SwiftyJSON or something similar. This is a more practical approach, where the article was somewhat of a thought experiment about separating concerns and avoiding `init?`.

As long as we're avoiding `init?`, the design that you choose mostly depends on your preference, goals, and existing architecture!

**Comment by iUtvikler** [comment]
Yeah I think maybe joining them will be a better fit in my use case, but I like the article the way it is.

The *phantom type* in the validator and *generics where clause* in the parse function taught me a few things!

Thanks!
